### ISSUE TITLE
TTS语音识别大量消耗CPU

### ISSUE THREAD

**Issue by Deniel-nice** [zixiiu/Digital_Life_Server#100]
我在调用TTS中的文字转音频的时候，如果文字需要转的太多或者几个问题一起转音频，就会直接把我的4核16G内存的服务器CPU拉满，不知道大家使用的如何，有没有相同问题交流一下

**Comment by mikeyang01** [comment]
用GPU啊

**Comment by Deniel-nice** [comment]
> 用GPU啊

是的 用GPU服务器解决了，感谢回复
