### ISSUE TITLE
Sentiment识别的结果说明有吗，情感具体是分为哪6个类别

### ISSUE THREAD

**Issue by user-ZJ** [zixiiu/Digital_Life_Server#106]

**Comment by zhuzihan728** [comment]
![image](https://github.com/zixiiu/Digital_Life_Server/assets/55835587/bac82d61-48b0-43f7-9eac-2fce8277ee6f)

**Comment by user-ZJ** [comment]
> ![image](https://private-user-images.githubusercontent.com/55835587/317298136-bac82d61-48b0-43f7-9eac-2fce8277ee6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1ODk5MjEsIm5iZiI6MTcxMTU4OTYyMSwicGF0aCI6Ii81NTgzNTU4Ny8zMTcyOTgxMzYtYmFjODJkNjEtNDhiMC00M2Y3LTllYWMtMmZjZTgyNzdlZTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAxMzM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OGZlOTBlZDA0M2U3ZDZlNzMxMjVlNzI3Yjg1MTA5OGZlMjZlZmI4MmYzYzExMzM2YzhhMWQwYWE0ZGEwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0dMBnIcErIXRiEVSxFv3rqnayax--lcIyqKc5DXmI6U)

感谢
