### ISSUE TITLE
三部分都整好了，应该怎么打包成一起交互呢

### ISSUE THREAD

**Issue by folbird** [zixiiu/Digital_Life_Server#18]
![QQ截图20230511224248](https://github.com/zixiiu/Digital_Life_Server/assets/121536642/1d4bac73-71d6-415c-b9dd-718f785b6695)

**Comment by Zlztai** [comment]
你这厉害啊，我只弄了第一本服务器，UE5和Launcher 牵扯其他东西，不会弄啊。 （要配置软件，我这笔记本电脑顶部不住啊）

**Comment by folbird** [comment]
我折腾了好久，之前也是一脸懵，现在算是有一点头绪了

**Comment by xiaoqiang0113** [comment]
顶一个,我也不会交互

**Comment by zixiiu** [comment]
交互是什么意思呢，UE部分填入本机ip和端口（38438） 就可以和派蒙对话了。

**Comment by xiaoqiang0113** [comment]
但是第2张图,数字生命启动器都是N/A啊

**Comment by zcliu12** [comment]
> 我折腾了好久，之前也是一脸懵，现在算是有一点头绪了

大哥，为啥我运行构建出来没有socketserver.exe呢

**Comment by folbird** [comment]
我用的pyinstaller打包的

**Comment by folbird** [comment]
> > 我折腾了好久，之前也是一脸懵，现在算是有一点头绪了
> 
> 大哥，为啥我运行构建出来没有socketserver.exe呢

我用的pyinstaller打包的

**Comment by zixiiu** [comment]
pyinstaller打包就行，spec文件已经写好了

**Comment by yiyang518** [comment]
> ![QQ截图20230511224248](https://user-images.githubusercontent.com/121536642/237725136-1d4bac73-71d6-415c-b9dd-718f785b6695.png)

![image](https://github.com/zixiiu/Digital_Life_Server/assets/49931274/4a65ebc6-eb42-459a-a616-7e3013105dc5)
这个UE怎么用啊，我打开时这个图

**Comment by petulat** [comment]
> 交互是什么意思呢，UE部分填入本机ip和端口（38438） 就可以和派蒙对话了。

@zixiiu 
Linux 服务端已经命令行启动好了，不懂客户端，UE部分怎么搞呢？
现在服务启动了，没有客户端 用不起来
