### ISSUE TITLE
感觉可以做个不需要GPU的版本，方便低配用户

### ISSUE THREAD

**Issue by cgsvv** [zixiiu/Digital_Life_Server#20]
看了一下，需要GPU的模块：

语音识别：可以直接用Windows自带的
情感分析：直接写在prompt里面让chatgpt返回
语音合成：也可以直接用Windows自带的（虽然效果一般，但速度估计会快，而且我试过直接cpu跑vits推理，速度其实也可以接受，毕竟是个400M的小模型）

UE这一部分不是很了解，但这种简单的动画应该不需要很好的GPU也可以完成吧

**Comment by zixiiu** [comment]
语音识别和情感分析都是onnx，把runtime装成CPU就是CPU推理了。vits可以尝试一下安装cpu版本的pytorch，应该是可以用的，只是会比较慢。

**Comment by DancingLeaf123** [comment]
我也需要低配版，请问，如何设置。目前我run bat提示需要N卡了
