### ISSUE TITLE
那个派蒙的语音模型文件怎么单独推理啊 

### ISSUE THREAD

**Issue by Zha-Miku** [zixiiu/Digital_Life_Server#32]
用了[MoeGoe](https://github.com/CjangCjengh/MoeGoe)
后显示报错了
这应该使用哪种的vits环境来推理啊

**Comment by LaiWX** [comment]
如果报错是`size mismatch for enc_p.emb.weight`
需要在paimon6k.json中symbols的"\u2026", "\u3105"之间加上\u300c和\u300d两个unicode，即
`"\u2026", "\u300c", "\u300d", "\u3105"`

**Comment by Zha-Miku** [comment]
大佬牛逼，可以了
