### ISSUE TITLE
客户端在哪个项目里面呀 有没有开源

### ISSUE THREAD

**Issue by super617** [zixiiu/Digital_Life_Server#39]
客户端在哪个项目里面呀 有没有开源

**Comment by zixiiu** [comment]
https://github.com/QSWWLTN/DigitalLife
开源，在这个项目里面

**Comment by petulat** [comment]
> https://github.com/QSWWLTN/DigitalLife 开源，在这个项目里面

服务端在Linux上使用命令成功启动。
客户端是安卓还是win呢？要用 [QSWWLTN/DigitalLife](https://github.com/QSWWLTN/DigitalLife) 自己编译吗？
