### ISSUE TITLE
SocketServer.exe构建问题

### ISSUE THREAD

**Issue by yiyang518** [zixiiu/Digital_Life_Server#52]
构建了怎么运行不了啊，用pyinsyaller  SocketServer.spec命令构建的
![image](https://github.com/zixiiu/Digital_Life_Server/assets/49931274/626b16f1-1607-49f6-ba98-17a516eb1d58)

**Comment by zixiiu** [comment]
运行的时候记得加参数，或者使用launcher打开。

**Comment by motane** [comment]
您好，请问解决了吗，我也遇到了同样的问题
