### ISSUE TITLE
我用的是自己的open ai key, 为啥提示是我撸羊毛，一小时后再问

### ISSUE THREAD

**Issue by DancingLeaf123** [zixiiu/Digital_Life_Server#55]
![image](https://github.com/zixiiu/Digital_Life_Server/assets/23498471/daa2065e-484d-411f-8ff0-191615e2c5cb)

**Comment by chichi087458** [comment]
我的是因为api免费额度在6月1日过期了......

**Comment by petulat** [comment]
> 

哦哦 那这个提示不太对 还以为是没用上自己的APIKey

**Comment by 1952448936** [comment]
您好，这个问题是咋解决的呢
