### ISSUE TITLE
大佬已经做好的beta版，不用自己去搞

### ISSUE THREAD

**Issue by wcpbruce** [zixiiu/Digital_Life_Server#80]
【我们做了个能对话的AI派蒙，免费给大家玩！-哔哩哔哩】 https://b23.tv/hlsn96J

    大家可以看看大佬已经做好的beta版，解压就可以用的，在b站视频下的123网盘和百度网盘里

**Comment by wcpbruce** [comment]
在视频简介里，百度网盘或123网盘

**Comment by ZYD20200827** [comment]
https://pan.baidu.com/s/1vuGkiSCzdTL4co0bH2XIKQ?pwd=bf91
https://www.123pan.com/s/MjA7Vv-m82i.html

**Comment by zixiiu** [comment]
难道你们不是从这个视频里面过来的吗。。。。
