### ISSUE TITLE
you have your own api key,great

### ISSUE THREAD

**Issue by ZYD20200827** [zixiiu/Digital_Life_Server#83]
显示“you have your own api key,great”正常吗

**Comment by ZYD20200827** [comment]
配置了代理可以用了

**Comment by HaSaKiYasuooo** [comment]
> 配置了代理可以用了
你好，为什么我启动的时候会有ASR 服务中止问题

**Comment by zixiiu** [comment]
自己提供key就会有这个提示。

**Comment by lichenyigit** [comment]
![image](https://github.com/zixiiu/Digital_Life_Server/assets/28697006/112d438f-b7f1-4d0a-9347-b4ec51fc1a7a)
我自己的key为什么会有这个提示？
